version: "3.8"
services:
  api:
    container_name: api
    env_file:
      - ./api/.env
    ports:
      - ${API_EXTERNAL_PORT}:${API_INTERNAL_PORT}
    depends_on:
      - mysql
  mysql:
    image: mysql
    container_name: mysql
    volumes:
      - ./mnt/mysql:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    command: --default-authentication-plugin=mysql_native_password --init-file /docker-entrypoint-initdb.d/setup.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - ${PMA_PORT}:80
    environment:
      PMA_HOST: ${PMA_DB_ENGINE}
      UPLOAD_LIMIT: 1000M
    depends_on:
      - mysql
