version: '3.8'
services:
  apis:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: npm run start:dev
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - ${API_EXTERNAL_PORT}:${API_INTERNAL_PORT}
